# Generated by Django 5.1.5 on 2025-01-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0002_hero_active_monster_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('damage', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='hero',
            name='skills',
        ),
        migrations.AddField(
            model_name='hero',
            name='skills',
            field=models.ManyToManyField(blank=True, to='Cards.skill'),
        ),
    ]
