# Generated by Django 5.1.5 on 2025-01-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0003_skill_remove_hero_skills_hero_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='skills',
            field=models.ManyToManyField(blank=True, to='Cards.skill'),
        ),
    ]
